# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  schedule:
    - cron: '0 1 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'
        cache-dependency-path: subdir/go.sum

    - name: Install dependencies
      run: |
        go get cmd/kaggle/.

    - name: make .env
      run: |
        touch .env
        echo "DISCORD_URL=${{ secrets.DISCORD_URL }}" >> .env

    - name: run go
      run: go run cmd/kaggle/main.go
